on:
  push:
    tags:
      - 'v*'

name: Release

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add aarch64 target
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
      - name: Build aarch64 binary
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu --config target.aarch64-unknown-linux-gnu.linker=\"aarch64-linux-gnu-gcc\"
          mv target/aarch64-unknown-linux-gnu/release/nmc nmc-aarch64
      - name: Build x86_64 binary
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-gnu/release/nmc nmc-x86_64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nmc-aarch64
            nmc-x86_64
