on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run tests
        run: go test -v ./...
      - name: Build binaries
        run: |
          GOOS=linux GOARCH=arm64 go build -o nm-configurator-arm64 ./...
          GOOS=linux GOARCH=amd64 go build -o nm-configurator-amd64 ./...
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nm-configurator-arm64
            nm-configurator-amd64
