on:
  push:
    tags:
      - 'v*'

name: Release

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build x86_64 binary
        run: |
          docker build -t nmc:amd64 --platform linux/amd64 .
          container_id=$(docker create nmc:amd64 --entrypoint /)
          docker cp $container_id:/app/target/release/nmc nmc-x86_64
          docker rm $container_id
          docker image rm nmc:amd64
      - name: Build aarch64 binary
        run: |
          docker build -t nmc:arm64 --platform linux/arm64 .
          container_id=$(docker create nmc:arm64 --entrypoint /)
          docker cp $container_id:/app/target/release/nmc nmc-aarch64
          docker rm $container_id
          docker image rm nmc:arm64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nmc-aarch64
            nmc-x86_64
